#FROM ai-studio-registry-vpc.cn-beijing.cr.aliyuncs.com/kube-ai/triton_with_ft:22.03
FROM ai-studio-registry-vpc.cn-beijing.cr.aliyuncs.com/kube-ai/triton_with_ft:22.03-main-2edb257e
RUN pip install transformers -i https://pypi.tuna.tsinghua.edu.cn/simple
